{{/*
Copyright Cyral, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.cyral.sidecar.certificates.ca.existingSecret -}}
{{- $secretName := printf "%s-ca-certificate" (include "common.names.fullname" .) }}
{{- $hostname := .Values.cyral.deploymentProperties.endpoint | default "sidecar.app.cyral.com" }}
{{- $ca := genCA $hostname 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "tls.crt" "defaultValue" $ca.Cert "context" $) }}
  tls.key: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "tls.key" "defaultValue" $ca.Key "context" $) }}
{{- end -}}
