{{- /*
Copyright Cyral, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if (include "cyral.createCredentialsSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-credentials-secret" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  clientId: {{ .Values.cyral.credentials.clientId | b64enc | quote }}
  clientSecret: {{ .Values.cyral.credentials.clientSecret | b64enc | quote }}
{{- end }}