{{/*
Copyright Cyral, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.cyral.sidecar.certificates.tls.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-selfsigned-certificate" (include "common.names.fullname" .) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  {{- $hostname := .Values.cyral.sidecar.dnsName | default "sidecar.app.cyral.com" }}
  {{- $cert := genSelfSignedCert $hostname nil (list (printf "*.%s" $hostname)) 3650 }}
  tls.crt: "{{ $cert.Cert | b64enc | b64enc }}"
  tls.key: "{{ $cert.Key | b64enc | b64enc }}"
{{- end -}}
